name = "wxchat"
main = "worker/index.js"
compatibility_date = "2025-06-17"

# 静态资源配置 - 使用正确的格式
[assets]
directory = "./public"
binding = "ASSETS"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "wxchat"
database_id = "34dd8abd-6ba1-418f-8617-172f41f2a21b"

# R2 存储桶绑定
[[r2_buckets]]
binding = "R2"
bucket_name = "wxchat"

# 环境变量配置（用于鉴权）
[vars]
# 访问密码（明文，直接在Cloudflare Workers控制台配置）
ACCESS_PASSWORD = "wxchat2026666"
# JWT密钥（用于会话管理）
JWT_SECRET = "a9f3b7d2e8c1f0a4b6d9e2c7f5a3b8d0"
# 会话过期时间（小时）
SESSION_EXPIRE_HOURS = "24"
# 最大登录尝试次数
MAX_LOGIN_ATTEMPTS = "5"


